### ISSUE TITLE
How to install Media_Build ? (DVB)

### ISSUE THREAD

**Issue by FightingForFun** [TinkerBoard/debian_kernel#12]
Good day.

I have a problem with installing media_build (from LinuxTV for Mygica T230 usb TV adapter):
```
make[2]: Leaving directory '/home/linaro/media_build/linux'
./scripts/make_kconfig.pl /lib/modules/4.4.71+/build /lib/modules/4.4.71+/build 1
Preparing to compile for kernel version 4.4.71
File not found: /lib/modules/4.4.71+/build/.config at ./scripts/make_kconfig.pl line 33, <IN> line 4.
Makefile:377: recipe for target 'allyesconfig' failed
make[1]: *** [allyesconfig] Error 2
make[1]: Leaving directory '/home/linaro/media_build/v4l'
Makefile:26: recipe for target 'allyesconfig' failed
make: *** [allyesconfig] Error 2
can't select all drivers at ./build line 525

```
I think maybe need Linux-headers for 4.4.71+ but i not found. 
Need help.

**Comment by FightingForFun** [comment]
Or how i can install media_build or put inside in Kernel?

**Comment by jamess-huang** [comment]
You can git clone the kernel source code
$ git clone https://github.com/TinkerBoard/debian_kernel.git
and then create a soft link to the source code which you just download.
$ ln -s ~/debian_kernel /usr/src/linux-headers-$(uname -r)
