### ISSUE TITLE
DS18B20 Temp Sensor

### ISSUE THREAD

**Issue by baker12** [TinkerBoard/debian_kernel#19]
Is this sensor now supported native in TinkerOS? I have the latest (2.0.7) installed and have enabled 1-Wire through the Config tool but I still do not see my device. Didn't know if I needed to compile any drivers or not.

**Comment by jamess-huang** [comment]
Hi, 
   It supported in the native TinkerOS. Please reference the below link.
   https://tinkerboarding.co.uk/wiki/index.php/DS18B20

**Comment by baker12** [comment]
Alright. I had saw that before and was confused if I needed to do that myself or not, but saw in the source code on here that it was all in there. I'll do some more checking and see why the sensor isn't showing up. Thanks!

**Comment by jamess-huang** [comment]
Hi,
   At the v2.0.7, you do not recompile kernel but if you want to change the default GPIO, then you need recompile kernel. Suppose you want to use the default GPIO, you just need do the section 3.1 of the below link.
https://tinkerboarding.co.uk/wiki/index.php/1-wire .

**Comment by baker12** [comment]
Figured out I was reading the wrong GPIO 17 (Read the number on the Pi-Cobbler I'm using and miscounted from the figure). Everything is working good now!
