### ISSUE TITLE
System "reboot" issue by using "sysrq"

### ISSUE THREAD

**Issue by sghazagh** [TinkerBoard/debian_kernel#2]
I have an "init" file for resizing the rootfs partition in first boot.
I need to use magic SysRq key "**`echo b > /proc/sysrq-trigger`**" to reboot the system after partition has resized.

The "sysrq" options in Kernel are enabled however, system cannot reboot.
It shut-downs the system immediately as expected but doesn't initiate the boot procedure.
Have to manually power-off and power-on the power source to make it boot again.

Can you please investigate and provide a solution?!
Thanks

**Comment by tido-** [comment]
for kernel 4.4 https://forum.armbian.com/index.php?/topic/3327-asus-tinkerboard/&do=findComment&comment=31067

**Comment by sghazagh** [comment]
Hi Tido,
Thanks for the reply.
But I downloaded the kernel after 5th/May so it should already have been fixed but it's not.
Can you please give me the commit or link showing the changes then I check and see if patched has applied?

I do appreciate your help.
(you always are helpful like what you did in Lemaker Forums :)

**Comment by tido-** [comment]
Hi sghazagh,

I also thought I have seen that name before - same to you, thank you.
It was not compiled with the fixes until now, see here: 
https://forum.armbian.com/index.php?/topic/3327-asus-tinkerboard/&do=findComment&comment=32887

**Comment by TinkerTeam** [comment]
Hi @sghazagh & @tido- ,

Thanks for your reply.
And it will be fixed in the next release.

**Comment by TinkerTeam** [comment]
Fix on 15a531028f80eef8f2385173ec39d370cac88486.
