### ISSUE TITLE
Does Tinker Board S supports TDM Audio mode?

### ISSUE THREAD

**Issue by ghost** [TinkerBoard/debian_kernel#20]
Tinker Board S has :

"Enhanced I2S pin with Slave mode and an improved software API for better compatibility"

But, I would like to know if the board can Support TDM mode :

"Normally digital audio is communicated between chips using I2S protocol. Two I2S streams can be used for quad channel, but to really step up to more channels, you need TDM protocol.
TDM, which stands for Time Division Multiplexing, communicates a frame of 256 data bits. For 44.1 kHz, this means the bit clock must be 11.3 MHz. Only 4 signals are used, one to transmit all 256 bits and another to receive all 256, a frame sync signal the marks where each 256 bit frame begins, and of course the 11.3 MHz clock."

Thanks
Lucas

**Comment by jamess-huang** [comment]
I am sorry that I forgot reply this question. The RK3288 cannot support TDM mode.
