### ISSUE TITLE
Update QMI driver

### ISSUE THREAD

**Issue by danilaeremin** [TinkerBoard/debian_kernel#21]
Request to update QMI_WWAN driver from original linux repo.

For support SIMCom 7600E module need to update driver.
{QMI_QUIRK_SET_DTR(0x1e0e, 0x9001, 5)},	/* SIMCom 7100E, 7230E, 7600E ++ */

**Comment by jamess-huang** [comment]
Hi, 
    It seems the QMI_QUIRK_SET_DTR function is supported from kernel 4.9, but our kernel version is 4.4.
    I am afraid it can not be updated. But you can try by yourself. For example, you can replace the qmi_wwan.c file and then try to fix the compile error.
