### ISSUE TITLE
Source code for the image

### ISSUE THREAD

**Issue by antmak** [TinkerBoard/debian_kernel#28]
What source code do you build the image `https://github.com/TinkerBoard/debian_kernel/releases/download/2.0.7/20180622-tinker-board-linaro-stretch-alip-v2.0.7.img.zip` from?

**Comment by jamess-huang** [comment]
We provide the u-boot and kernel source code. Please find the source code below and checkout to tag 2.0.7.
https://github.com/TinkerBoard/debian_kernel
https://github.com/TinkerBoard/debian_u-boot
