### ISSUE TITLE
Upgrade to Debian Buster, Debian 10, Debian stable?

### ISSUE THREAD

**Issue by apivovarov** [TinkerBoard/debian_kernel#60]
Looks like Tinker Debian OS v2.1.16 is based on "oldstable" Debian 9 (Stretch).
It has quite old glibc 2.24.

Any plans to switch Tinker Debian OS to Debian 10 (Buster)? Which is Debian stable now.

Hardware: Tinker Board (RK3288)

Should I try this OS https://github.com/TinkerBoard2/kernel/releases/tag/tinker_board_2-debian_10-2.0.0 ?

**Comment by asus-leslieyu** [comment]
We do plan for Debian Buster and are working on it now.
tinker_board_2-debian_10-2.0.0 is for Tinker Board 2/2S instead of Tinker Board (S).
